name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: core_banking
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo 'waiting for mysql to be ready...'
          sleep 5
        done

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: core_banking
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: npm test
      working-directory: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    # - name: SSH into AWS server and clone repository
    #   env:
    #     AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
    #     AWS_HOST: ${{ secrets.AWS_HOST }}
    #     AWS_USER: ${{ secrets.AWS_USER }}
    #   run: |
    #     echo "${{ env.AWS_PRIVATE_KEY }}" > private_key.pem
    #     chmod 600 private_key.pem
    #     ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.AWS_USER }}@${{ env.AWS_HOST }} << 'EOF'
    #       cd ~
    #       git clone https://github.com/yourusername/yourrepository.git
    #       cd yourrepository/backend
    #       npm install
    #       npm start
    #     EOF
    #   shell: bash